### ISSUE TITLE
Tinker box installation problem

### ISSUE THREAD

**Issue by sogg485** [Patrick-81/NAFABox#6]
Hi Patrick,

Firstly, I would like to thank you for all the work you have done which will greatly help the astronomical community.:)

I am having some issues installing the master.zip into the os, 

I could not find the ./go.sh anywhere in the zip and after running the ./Install, there are files duplicated for example there are two phd2 and kstar.

The wifi for hotspot is not really working. Tried connecting my phone or laptop and it fails connection. Therefor I won’t be able to run VNC viewer on it.

I really hope this can be resolved. 
Thank you very much.

Regards,
Girit

**Comment by dragonlost** [comment]
Hello.

The go.sh is no longer valid. We have not yet had the time to update the online documentation. So you have to rely on the readme for the installation.

For the duplication, it is indeed a problem because one creates racourcies for all that one installs in the office and in the menu. On the other hand certain application the background already in the menu which duplicates.

For the hotspot, we have a lot of problems with that. In the BETA version we solved this problem with the armbian script.
So I invite you to use armbian-config to create the hotspot.

**Comment by sogg485** [comment]
Hi,

I have tried the following method and also used the armbian-config technique. 
Here is the method i followed:

$ sudo armbian-config ( for french azerty keyboard : sudo qr,biqn)config )
go to system -> nightly and valid

There is no more files duplication, and i am able to connect to the tinkerbox when i create a new hotspot. But i am still unable to connect tinkerboard vnc server from my laptop or phone.

There is also another issue. the menus on the top and bottom of the operating system has disappeared. so i had to manual use terminal to shut down and restart. 

Regards,
Girit

**Comment by dragonlost** [comment]
I just switched on the new version of the indi driver for Atik camera now that it is officially released.
